### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by LeonSt3** [LukeSkywalker92/MMM-DWD-WarnWeather#21]
Hallo!
Ich habe schon viel zu Konfigurieren versucht aber bekomme dieses Modul einfach nicht zum Laufen! Bekomme immer diesen Fehler.
Kann mir irgendjemand dort weiterhelfen?

[LOG]    Whoops! There was an uncaught exception...
[ERROR]  SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_helper.js:64:22)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)

Config: 
	{
				module: 'MMM-DWD-WarnWeather',
				position: 'topCenter',
				header: 'Wetterwarnungen',
				config: {
					region: "Aachen",
		                        changeColor: true,
		                        interval: 10 * 60 * 1000, // every 10 minutes
		                        loadingText: "Warnungen werden geladen...",
		                        displayRegionName: false,
		                        noWarningText: "Keine Warnungen"

				}

**Comment by lavolp3** [comment]
GLeicher Fehler bei mir. Aber erst seit kurzem.

**Comment by Moskito99** [comment]
Funktioniert seit ca. 2-3 Tagen nicht mehr.
Gleicher Fehler wie oben:
```
[2020-06-17 07:10:08.725] [ERROR]  SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_helper.js:64:22)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
```

Modul ist aktuell kaputt!

**Comment by lavolp3** [comment]
Das Modul funktioniert (anscheinend) bei Eingabe der warnCellID.
Die Dokumentation gibt die Suche mit Namen (DWD_NAME) auch nicht mehr her.
Hier die csv Datei mit allen Gemeindeschlüsseln. 
https://www.dwd.de/DE/leistungen/opendata/help/warnungen/cap_warncellids_csv.csv?__blob=publicationFile&v=3
Der jeweilige Schlüssel muss als warnCellID in der config angegeben werden.

**Comment by Moskito99** [comment]
> Das Modul funktioniert (anscheinend) bei Eingabe der warnCellID.
> Die Dokumentation gibt die Suche mit Namen (DWD_NAME) auch nicht mehr her.
> Hier die csv Datei mit allen Gemeindeschlüsseln.
> https://www.dwd.de/DE/leistungen/opendata/help/warnungen/cap_warncellids_csv.csv?__blob=publicationFile&v=3
> Der jeweilige Schlüssel muss als warnCellID in der config angegeben werden.

Die Liste ist leider sehr durcheinander und nicht eindeutig!
Es gibt jeden Ort/Region zweimal. Ich mußte die warnCellID mit der 8 am Anfang nehmen, die 1 hatte nicht funktioniert.
Besser ist, die warnCellID von hier zu suchen: 
https://maps.dwd.de/geoserver/dwd/wms?service=WMS&version=1.1.0&request=GetMap&layers=dwd:Warngebiete_Gemeinden&styles=&bbox=5.876914,47.270362,15.037507,55.044381&width=1024&height=868&srs=EPSG:4326&format=application/openlayers#toggle
Wenn man dort auf die Region klickt bekommt man die richtige WARNCELLID unterhalb der Karte angezeigt....

**Comment by LeonSt3** [comment]
Vielen Dank für die schnelle Antwort! Hat funktioniert mit der warnCellID!
