### ISSUE TITLE
Ort nicht gefunden

### ISSUE THREAD

**Issue by chris-23** [LukeSkywalker92/MMM-DWD-WarnWeather#30]
Hi, leider wird bei meinem Spiegel seit kurzem der Ort nicht gefunden. Es wird nur "Ort nicht gefunden. Warnungen werden geladen" angezeigt. 
Bis dahin haben die Warnungen mit region und Kurzname in der config funktioniert. Ich habe auch die warnCellID ausprobiert, aber das ändert auch nix. 
Eventuell damit verbunden, in der mm-error.log steht:

> [05.06.2021 21:07.20.893] [ERROR] Whoops! There was an uncaught exception...
[05.06.2021 21:07.20.900] [ERROR] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_helper.js:82:22)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)

**Comment by CGabo** [comment]
Hi,
Dito, same error seit heute abend.

[05.06.2021 23:18.44.440] [ERROR] Whoops! There was an uncaught exception...
[05.06.2021 23:18.44.488] [ERROR] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_helper.js:82:22)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-DWD-WarnWeather/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)

Ist es nicht eher ein DWD API Problem?

**Comment by CGabo** [comment]
Im query dwd:Warngebiete_Gemeinden/Kreise, wird die WARNCELLID nicht mehr zurückgegeben.
-> mal schauen ob dies nur temporär so ist. Habe jedenfalls bei DWD nichts gefunden, was auf eine Umstellung hinweist.

**Comment by magic21nrw** [comment]
Same here.

**Comment by lxne** [comment]
Same here.

**Comment by det-box** [comment]
Same here.

**Comment by det-box** [comment]
Same here.

**Comment by LukeSkywalker92** [comment]
Same for me....maybe i will find some time to have a look...but help is welcome =)

**Comment by chris-23** [comment]
Works again for me, probably this was a problem on the DWD server side. Thanks for the feedback :)
